syntax = "proto3";

package runuram.proto;

import "telemetry.proto";
import "events.proto";
import "gamemap.proto";
import "user.proto";

message Envelope {
  oneof payload {
    events.PingMessage ping = 1;
    events.PongMessage pong = 2;

    telemetry.LocationBatch location_frame = 3;
    telemetry.LocationBatchAck location_frame_ack = 4;

    events.StartRunRequest start_run_request = 5;
    events.StartRunResponse start_run_response = 6;
    events.FinishRunRequest finish_run_request = 7;
    events.FinishRunResponse finish_run_response = 8;

    gamemap.SubscribeViewportRequest subscribe_viewport_request = 9;
    gamemap.SubscribeViewportResponse subscribe_viewport_response = 10;
    gamemap.HexagonCaptureEvent hexagon_capture_event = 11;
    gamemap.GetHexagonDetailsRequest get_hexagon_details_request = 12;
    gamemap.HexagonDetailsResponse hexagon_details_response = 13;

    user.GetUserProfileRequest get_user_profile_request = 14;
    user.UserProfileResponse user_profile_response = 15;
  }
}
