syntax = "proto3";

package runuram.proto;

import "telemetry.proto";
import "events.proto";
import "gamemap.proto";
import "user.proto";
import "history.proto";

message Envelope {
  oneof payload {
    // 1. Телеметрия забега
    telemetry.LocationBatch location_frame = 1;
    telemetry.LocationBatchAck location_frame_ack = 2;

    // 2. Управление жизненным циклом забега
    events.StartRunRequest start_run_request = 3;
    events.StartRunResponse start_run_response = 4;
    events.FinishRunRequest finish_run_request = 5;
    events.FinishRunResponse finish_run_response = 6;

    // 3. Карта и стриминг гео-данных
    gamemap.SubscribeViewportRequest subscribe_viewport_request = 7;
    gamemap.SubscribeViewportResponse subscribe_viewport_response = 8;
    gamemap.HexagonCaptureEvent hexagon_capture_event = 9;
    gamemap.GetHexagonDetailsRequest get_hexagon_details_request = 10;
    gamemap.HexagonDetailsResponse hexagon_details_response = 11;

    // 4. Профиль и статистика
    user.GetUserProfileRequest get_user_profile_request = 12;
    user.UserProfileResponse user_profile_response = 13;

    // 5. История пробежек и детали маршрутов
    history.GetUserRunsRequest get_user_runs_request = 14;
    history.GetUserRunsResponse get_user_runs_response = 15;
    history.GetRunDetailsRequest get_run_details_request = 16;
    history.GetRunDetailsResponse get_run_details_response = 17;
  }
}