syntax = "proto3";

package user;

import "common.proto";

message GetUserProfileRequest {
  uint64 user_id = 1; // 0 = запросить свой собственный профиль
}

message UserProfileResponse {
  common.Status status = 1;
  uint64 user_id = 2;
  string username = 3;
  string email = 4;
  string player_color_hex = 5;
  uint64 team_id = 6;
  string team_tag = 7;
  
  // Агрегированная статистика бегуна
  double total_distance_meters = 8;
  int64 total_duration_seconds = 9;
  int32 total_runs = 10;
  int32 total_uram_points = 11;
  int32 current_held_hexagons = 12; // Сколько ячеек держит прямо сейчас
}